### ISSUE TITLE
Access

### ISSUE THREAD

**Issue by bjfultn** [semaphoreP/codeastro#1]
@semaphoreP @sblunt could one of you give me write access to this repo?

**Comment by sblunt** [comment]
@semaphoreP I think you have to do this-- I don't have access to the settings.

**Comment by semaphoreP** [comment]
@bjfultn Github says you have a pending invite you haven't accepted yet. Try this link (https://github.com/semaphoreP/codeastro/invitations) or digging through your emails?

**Comment by bjfultn** [comment]
Try again now. I did find the invite and clicked it, but it said it expired. Maybe that cleared it on your end.

**Comment by semaphoreP** [comment]
Just send you another invite

**Comment by bjfultn** [comment]
Got it, I'm in. Thanks!
