### ISSUE TITLE
Day 2 | Gitflow Lesson Plan Review

### ISSUE THREAD

**Issue by belindathemoon** [semaphoreP/codeastro#100]
### How clear is the material? What’s confusing?
The illustrations are helpful, but I would suggest adding a slide at the beginning, or right after "how it works", defining terminology. I remember last year that people were confused about the differences between features and commits, and some were confused what a branch was. For those of us that love project management and logical processes, this is like flame to a moth, but if you're not used to thinking about process or order of operations, some additional discussion/description about the general process in plain language, and then definitions of the terminology would go a long way. I would also suggest including a real-world example of how this process would work, and why it's helpful—maybe even two examples—one about working with other developers, and one about working by yourself, but releasing code to users.

I really like the last two slides. My only suggestion for these would be to change it to a numbered list to make clear the steps.

### Are we assuming any knowledge that we shouldn’t be? Where should we add background info?
I kind of already answered that above, but perhaps even briefly talking about development process/project management in a general sense could be useful. 

I also think anyone who has heard of github and not used git or github may be intimidated by it (I was), and may also think it is more complicated than it is. I think you're already touching on it with the slide "Gitflow is a way of using Git and GitHub" but spending some extra time here on what git is and what github is could be helpful.

### Is the structure of the lesson engaging? Are there any parts that are unnecessary/boring/too long?
I like the "type along" style of the lesson. I think it is very engaging—and does go by quickly!

### How much time did it take you to complete the assignments?
My terminal was otherwise occupied while I was reviewing so I didn't time it, but I think for participants just running through a first-time test and not making actual feature commits, it shouldn't be more that 30 minutes (I would think more like 15 minutes unless they get stuck).

**Comment by belindathemoon** [comment]
I just realized that some of my suggestions are probably covered in the "Mechanics of git" lesson—if that's the case, then great job! :)

**Comment by sblunt** [comment]
Thanks for the excellent suggestions! I implemented a bunch of these changes, and also moved the presentation from keynote to google slides. Check it out when you have a chance and let me know what you think!

**Comment by sblunt** [comment]
Closing because I believe these were addressed, but please reopen if additional comments/suggestions!
