### ISSUE TITLE
Day 3 | Review: Releasing Code

### ISSUE THREAD

**Issue by belindathemoon** [semaphoreP/codeastro#106]
This is a difficult day, because there is a good chance that most people won't be ready to release yet, and may not even be entirely sure what dependencies they need to put into their requirements.txt file. I think have a clear set of steps will help—I like the slide of activities at the end, and would suggest creating a similar slide near the beginning of the presentation to show very clearly, here is what you need to do to get from some code you've written to a released package. Like a checklist.

I found the slides on the setup.py file and __init__.py file to be a little confusing. On slide 12, you note that an __init__ file tells setuptools that the code in this directory is a python package. I'm not actually sure if this is true, but I think you have to create the __init__ files before creating the setup file, right? If that's correct, then I would suggest going in that order. If that's not correct, then I would take out that note. Additionally, I like the example of the minimal setup script, but I think some notations about what each part is doing would be helpful to make it feel less like a black box. Lastly, a sample __init__ would be similarly helpful.

I can't think of any additional background knowledge to add. I think everyone is excited (but also nervous) about this part.

As far as timing, I think the actual creation of these files doesn't take more than an hour, but I would suggest really encouraging people to do a first release that is "not totally finished" just to get practice doing this. My group last year was really hesitant to release any code until it was completely done, and as a result, we didn't get much practice with putting the package together and releasing. Some people will feel like they are behind at this point, and so just remind them that it's low stakes and better to just do a release today so that they can practice putting the package together. They can do a new release tomorrow!

Also one minor thing that shouldn't matter, but I just noticed there is a typo in the title of slide 14. :)

**Comment by Palma-Bifani** [comment]
(I will post my review under this other one, to avoid opening too many issues)
- How clear is the material? What’s confusing?

I like it a lot. Maybe the twine part could be presented in more detail. When I was organizing a similar workshop for the Chilean community, we made a jupyter notebook explaining some of the files and the install process in more detail (see link below)

[https://github.com/Science-and-Commit/Workshop_2022/blob/main/4_code_profilling_and_releasing/releasing_code.ipynb](https://github.com/Science-and-Commit/Workshop_2022/blob/main/4_code_profilling_and_releasing/releasing_code.ipynb)

- Are we assuming any knowledge that we shouldn’t be? Where should we add background info?

The only thing I can think about is that they may not be ready with the package and therefore they will not be able to complete this task in the given activity time... but they can complete it afterwards. 

- Is the structure of the lesson engaging? Are there any parts that are unnecessary/boring/too long?

I think this is one of the most expected lessons of the workshop! They will be very interested.

- How much time?

This depends a lot. If their package is ready this will be fast (30 min?), but probably they will not be able to complete this activity during the time of the lesson.

**Comment by sblunt** [comment]
Thanks so much to both of you for the excellent feedback! I've tried to implement your suggestions in the google slides. Paulina, I'd love to include a link to your version of this activity if that's ok with you!

**Comment by Palma-Bifani** [comment]
Sure! Feel free to include it, but it's in spanish :)
