### ISSUE TITLE
Software Testing Review (Day 4, 2022)

### ISSUE THREAD

**Issue by Devagio** [semaphoreP/codeastro#107]
The slides and the activity are excellently structured, and touch upon all intended topics in a very accessible, interactive way. In my opinion, none of the content or structure needs to change. 
Slides 6 and 8 however may be a little overwhelming for some if enough time is not spent explaining the code. Adding comments / docstrings to the code would go a long way, especially if some participants' attention gives out during the explanation. 
Also, the "This Link" on slide 9 doesn't seem to work for me.

The slides allocate 15+10 minutes for the think-pair activity, while the notebook says 10+5 minutes. I feel it is important to have 15+10 minutes for the activity and the time allocation mentioned in the notebook needs changing, especially since most will be writing tests for the first time. 
The notebook assumes no knowledge we would not expect the participants to be familiar with (assuming we explicitly mention that is ALWAYS okay to look up documentation / definitions during these activities), it is simple enough to not distract them from the purpose of the exercise.

**Comment by sblunt** [comment]
Thanks so much! I've made the changes you suggested to the colab and slides. I'll definitely spend some time going over the test code slides verbally, and I've added docstrings to them following your suggestion.

I just checked the link on slide 9 again, and it does seem to be working for me. Could you try it again? 

I'll close this for now, but feel free to reopen if you have additional thoughts/suggestion!
