### ISSUE TITLE
Code Profiling Review (Days 3, 2022)

### ISSUE THREAD

**Issue by Devagio** [semaphoreP/codeastro#108]
The notebook is brief and touches on all intended topics very clearly, in sufficient depth, and without fluff. There is absolutely no assumed knowledge, except possibly the one-time fleeting mention of MKL/BLAS.

"If you speed up something that takes 50% of the runtime by a factor of 100, you speed up the code by a factor of 2." I feel saying "speed up by a factor of 100" could lead to unrealistic expectations and aims, especially since this is the first time we are mentioning speeding up a part of the code. A more mellow example like "speeding it up by a factor of 2 will reduce runtime by 25%" will drive home the same point.

The example under "runtime" in "Code Performance Extrapolation" seems too idealized, so it may be helpful to mention that there will most likely be deviations, especially at lower values of N, and hence it is advisable to test a fairly broad range on N.

**Comment by semaphoreP** [comment]
Thanks @Devagio! Just pushed some changes in commit 6da1c5 that incorporated your suggestions!
