### ISSUE TITLE
Parallelism Review (Day 4, 2022)

### ISSUE THREAD

**Issue by Devagio** [semaphoreP/codeastro#109]
Under "Before we begin with multiprocessing...", typo in the first bullet point: "only only" -> "only one". In the 3rd point, "lines with multiprocessing calls need to be wrapped in something like..." I feel this should be slightly elaborated (answering questions like why so, or what this wrapping does).
Typo in "Threads vs Processes": "complciated" -> "complicated".

The activity is simple, to the point, and assumes no knowledge that wasn't taught in the first 3 days. The other sections of the notebook are clear, but not as engaging as other lessons, we might want to look to shorten the content if the topic is difficult to make more engaging (eg. making the "Extended Cut" optional).

**Comment by semaphoreP** [comment]
Thans @Devagio! I've incorporated these changes. And yes, the extended cut is intended to be optional, as it's quite technical and only relevant to folks who really want to do more advanced parallel programming.
