### ISSUE TITLE
Curriculum Review: Day1 Matplotlib and Astropy

### ISSUE THREAD

**Issue by pranav-satheesh** [semaphoreP/codeastro#110]
### How clear is the material? What’s confusing?

This matplotlib and astropy portions are very well structured and easy to understand. The activities are also very engaging. I have a small comment for people using google colab. The matploltib activities use `orbitize` so maybe we should add a line `pip install orbitize` in the cell above. 

### Are we assuming any knowledge that we shouldn’t be? 

The matplotlib section is very basic and easy to understand but the astropy section involves fits files. Although the activities involving fits files are pretty basic, maybe we should explain what fits files are during the walkthrough. Also, explain the output of `hdul[0].header`.

### Is the structure of the lesson engaging?
Yes!!

### how much time did it takes you to complete the assignments? 

Around 5-10 minutes for the matplotlib and ~ 10 minutes for the astropy assignments.

**Comment by sblunt** [comment]
Thanks so much Pranav! I added a line to pip install orbitize in PR #96, and added some info about fits files in PR #125. Feel free to reopen if you have additional thoughts/suggestions!
