### ISSUE TITLE
Day 1: Development Environments

### ISSUE THREAD

**Issue by shubhagrawal30** [semaphoreP/codeastro#111]
**How clear is the material? What’s confusing?**

From reading the lesson plan document and from what I remember from last year, I think this section is solid, with its strongest part being the demos we plan on doing. The demos for VS Code are especially useful due to the insane amount of options available on one screen.

I think if someone was not able to attend the live session or have an access to a recording, the text itself in the notebook is tough to follow. Perhaps including a link to the recordings in the notebook itself (after the workshop) would be useful. I also think that there is a lot of jargon in the text itself that someone with no knowledge of Git or SSH might be confused by.

**Are we assuming any knowledge that we shouldn’t be? Where should we add background info?**

I think just letting people know in the text itself that if _they don't understand Git or SSH, that is fine because we will be covering them nicely later on_ would be ideal. I think I would have been stressed on Day 1 if I was unfamiliar with it. 

**Is the structure of the lesson engaging? Are there any parts that are unnecessary/boring/too long?**

I think that, with the demos, the lesson will turn out great!

**how much time did it take you to complete the assignments? Keeping in mind that most participants will likely take more time than you, how much time should we suggest that participants spend on each activity?**

I think this is not relevant for this lesson? on a related note though, I really like the distribution of time between VS Code, text editors, and Jupyter, I think VS Code definitely needs the most time for a demo.

**Comment by semaphoreP** [comment]
Thanks! I added some references/context in the text when describing the VS Code features in PR #124. We want to try to release the recordings publicly this year, and if so, we can directly link it into the notebook.
