### ISSUE TITLE
Day 1: Development Environments Review

### ISSUE THREAD

**Issue by vighnesh-nagpal** [semaphoreP/codeastro#112]
**How clear is the material? What’s confusing?**

I think that the notebook is overall pretty clear. However, there are a few terms in there, such as 'field' that may benefit from a quick definition. A second point is the use of the keyword 'self' in OOP: I remember struggling with understanding what that was and when we need to explicitly include it in (say) the arguments for a method. The rules for that are fairly consistent, so I think the activity would benefit from a quick explanation of what 'self' is actually referring to. 

**Are we assuming any knowledge that we shouldn’t be? Where should we add background info?**

In addition the ones mentioned above, there are a few references to SSH, which is something that participants may not be familiar with.

**Is the structure of the lesson engaging? Are there any parts that are unnecessary/boring/too long?**

The lesson is pretty engaging over all, and in my past experience as a student/TA, the OOP activities are the highlight!

**how much time did it take you to complete the assignments? Keeping in mind that most participants will likely take more time than you, how much time should we suggest that participants spend on each activity?**

It took me in the 5-10 min range, so I think we should give participants 10-15 mins

**Comment by semaphoreP** [comment]
Thanks! I added a couple of lines of docstring in the example that I will also explicitly mention during the lesson regarding `self`. I also added a one-line explanation of SSH. PR #124
