### ISSUE TITLE
Day 2: Mechanics of Git

### ISSUE THREAD

**Issue by physical256** [semaphoreP/codeastro#113]
### How clear is the material? What’s confusing?

I think the sides overall are clear although given this is the first introduction to the underlying processes of git short of pull and checkout participants have maybe some real-world analogy would help to clarify for some participants. I like the use of illustrations but I know from the past as a participant that I never really 'got' git until I had done a much more interactive first-principles approach to how it works, maybe that is just me. 

### Are we assuming any knowledge that we shouldn’t be? Where should we add background info?

I don't think so, you mention within the slides that Git is quite esoteric at times and has been built to do things that 99% of users will very rarely have to do. Relating back to the previous section may be a none code example (wrapping presents putting them under a tree etc) would be a useful thing to add given some of our participants have no experience of code beyond the typical scientific programming. 

### Is the structure of the lesson engaging? Are there any parts that are unnecessary/boring/too long?

It is engaging although I strongly suspect we could be achieving the same learning outcomes with a more interactive session I would maybe like a little more discussion as to things like pull vs fetch and merge etc because I think that really helps to understand what is actually going on during a pull (and occasionally things break in a way that you will need to do it old school). I have some ideas for interactivity but we can discuss these offline :) 

### how much time did it takes you to complete the assignments? Keeping in mind that most participants will likely take more time than you, how much time should we suggest that participants spend on each activity?

This is a difficult one to answer really as I am very familiar with the processes and mechanics of git with each example really not taking long at all because I knew. I suspect 3-5 minutes an example is probably a reasonable time for someone with limited exposure to git.

**Comment by semaphoreP** [comment]
@sblunt are you doing a demo of Git in the gitflow section now? If so, probably don't need to also have a demo here.

**Comment by sblunt** [comment]
Yeah I am planning to do a demo of git in the gitflow lesson (just making a commit from vs code)

**Comment by semaphoreP** [comment]
Ok, I'll do a short command line demo just to show some basic commands, but I'd still like to focus on the theory here, because having a mental model of how git works is useful to troubleshot git issues on your own.
