### ISSUE TITLE
Day 2: Gitflow

### ISSUE THREAD

**Issue by physical256** [semaphoreP/codeastro#114]
### How clear is the material? What’s confusing?
A recap of the terminology would be useful towards the start. I appreciate this is coming off the back of the mechanics of git lesson but it comes into the tell them, tell them again, tell them what you told them repetition model and I know from past experience it was still not really clear at this stage in learning git what everything did. 

The illustrations are very good and very helpful but either on the gitflow or the git mechanics lesson a plain language analogy of the processes of git would be helpful (wrapping presents putting them under a tree etc) I suspect it may be better placed on the mechanics of git but could equally be helpful here. ¿Por qué no los dos?

### Are we assuming any knowledge that we shouldn’t be? Where should we add background info?
I think the only real assumption that is made across both of these sessions is that people already kind of have a working understanding of git and want to learn slightly more advanced under-the-hood mechanics a lot of our participants this will be their first exposure to version control at all. 

### How much time did it take you to complete the assignments?
10 minutes, again I suspect participants will take longer 15-30 minutes probably depending on their experience.

**Comment by sblunt** [comment]
Thanks for the excellent suggestions! I implemented a bunch of these changes, and also moved the presentation from keynote to google slides. Check it out when you have a chance and let me know what you think!

**Comment by sblunt** [comment]
Closing because I believe these comments were addressed, but please reopen if additional thoughts/suggestions!
