### ISSUE TITLE
Day 4: Discrimination in Software

### ISSUE THREAD

**Issue by physical256** [semaphoreP/codeastro#115]
### How clear is the material? What’s confusing?
I think the view, on the whole, is balanced (all be it with the slight caveat that it is slightly American leaning). Ironically the implicit bias test is not particularly accessible for people with ADHD I really struggled there but the results discussion is interesting and important. I can't really answer for how long the tests took to do as I could not manage to complete them (I really hate adhd brain some times).

I think it may be worth adding that the biased nature of some software is not a strictly American problem as some people still have the impression that this is the case. See Met police use of facial recognition [](https://bigbrotherwatch.org.uk/2022/03/cressida-dick-challenged-by-campaigners-in-botched-facial-recognition-photo-op/)

### Are we assuming any knowledge that we shouldn’t be? Where should we add background info?
the assumption is being made that people inherently know what discrimination is which is fair. I suspect going over terms such as conscious bias, unconscious bias etc may be useful as this is a thing people can often be confused about. I know from my previous ED&I work that a lot of people still have the view that only conscious acts can be discriminatory but maybe that is a culture difference between America and bits of Europe. I know America is somewhat more advanced in ED&I.

### Is the structure of the lesson engaging? Are there any parts that are unnecessary/boring/too long?
As above I really struggled with the implicit bias test due to my disability I really can't judge how long that is going to take people to complete. I am assuming this will follow a fairly discussion-based format and so will be perfectly engaging.

**Comment by semaphoreP** [comment]
Thanks @physical256! I changed up the activity to be something different rather than the implicit bias test. I also added a slide on implicit/explicit bias.
