### ISSUE TITLE
Day 4: Parallel Programming

### ISSUE THREAD

**Issue by physical256** [semaphoreP/codeastro#116]
### How clear is the material? What’s confusing?
Content is clear and well presented I love the interactive format notebooks provide. 

### Are we assuming any knowledge that we shouldn’t be? Where should we add background info? 
No not really by this stage in the programme people should be relatively happy with this although it may be a struggle for some and take a while. 

### Is the structure of the lesson engaging? Are there any parts that are unnecessary/boring/too long?

Yes yes yes, I love the interactive formats that notebooks provide. There is plenty of background information but people can skim if they need to and go back to it it's worked really well. 

### how much time did it takes you to complete the assignments? Keeping in mind that most participants will likely take more time than you, how much time should we suggest that participants spend on each activity?

It took me 40 minutes and that was with some slightly odd bugs to try and figure out I suspect others will take a similar if not slightly longer time first time as I had no experience with multiprocessing (I've always used threads in the past).

**Comment by semaphoreP** [comment]
Thanks for reviewing!
