### ISSUE TITLE
Day 1 Review: Development Environments

### ISSUE THREAD

**Issue by jeaadams** [semaphoreP/codeastro#118]
**How clear is the material? What’s confusing?**

I think this lesson is super clear! I remember the demos being really easy to go through. 

**Are we assuming any knowledge that we shouldn’t be? Where should we add background info?**

I don't think any prior knowledge is assumed. However, if I had to guess based on previous years, VS Code will be the newest to most people vs notebooks or plain text editors. It might be worth spending some extra time there so people can feel a tad more comfortable with it. Also, I don't remember if this is done in the demo, but I think it's pretty cool that we can open notebooks in vs code. I don't always do it, but it can be really helpful when I'm trying to code quickly to just switch between a module I'm writing and my notebook. 

**Is the structure of the lesson engaging? Are there any parts that are unnecessary/boring/too long?**

Very engaging! Short + sweet! 

**How much time did it take you to complete the assignments? Keeping in mind that most participants will likely take more time than you, how much time should we suggest that participants spend on each activity?**

I think reading through really only took a minute or two. However, with the demos, I think it's perfectly fine for this lesson to be as long as it needs to be for students to feel comfortable.

**Comment by semaphoreP** [comment]
Thanks! We moved away from VS Code notebooks to Collaboratory, but I added a bullet point that you can use VS Code to open notebooks and will aim to do a short demo of it.
