### ISSUE TITLE
Day 1 Review: Programming Paradigms

### ISSUE THREAD

**Issue by jeaadams** [semaphoreP/codeastro#119]

**Comment by jeaadams** [comment]
**How clear is the material? What’s confusing?**

I really love this lesson! I wish I had something like it when I first started programming. I would say it's pretty clear.

**Are we assuming any knowledge that we shouldn’t be? Where should we add background info?**

I think this lesson does a great job stressing what objects are vs functions, and how they're both useful. However, I think we're assuming a small bit of background info in the physics + code solution of the problem. I remember helping a group with this last year, and I think they wound up spending a lot of time thinking about how they were going to answer the physics and math of the question, which ended up diluting the overarching programming point a bit. _I love the bit of pseudocode help in the cell_. Would it be at all possible to add something like this up front in the markdown as well? e.g. after the first bullet point under 'Goal', we might consider saying "Some equations to help you advance the ball by one timestep are pseudocoded below. Put this in some kind of a loop to find how long it takes to go from 10 meters to less than 0 meters. "  
 
**Is the structure of the lesson engaging? Are there any parts that are unnecessary/boring/too long?**

Super engaging and fun!

**How much time did it take you to complete the assignments? Keeping in mind that most participants will likely take more time than you, how much time should we suggest that participants spend on each activity?**

It took me about 10 minutes to work through the whole lesson while reading everything closely. Perhaps we can give participants 20 - 30 minutes to make sure they get to take their time with everything as a group?

**Comment by semaphoreP** [comment]
Thanks! I added a couple of hints in the instruction to reference the psuedocode and making a for loop. See PR #124
