### ISSUE TITLE
Day 1: Programming Paradigms

### ISSUE THREAD

**Issue by shubhagrawal30** [semaphoreP/codeastro#120]
**How clear is the material? What’s confusing?**

The text seemed pretty clear. I think the one thing I would add is a real-life analogy to an object. Something like, if a car is a class / blueprint, then different models are inherited classes, and each individual car on the road is an object. Then, add on things like cars have different attributes like color, number of seats, engine types, and different behaviors like drive or brake. That could be useful to explain OOP. 

**Are we assuming any knowledge that we shouldn’t be? Where should we add background info?**

I do not think so. Perhaps some people do not fully get the examples such as "self.velocity" or what astropy is.

**Is the structure of the lesson engaging? Are there any parts that are unnecessary/boring/too long?**

I think the lesson is pretty nicely constructed. I do think we can spend a little bit more time on explaining the functional programming demo (because the students are not working on it themselves).

**how much time did it take you to complete the assignments? Keeping in mind that most participants will likely take more time than you, how much time should we suggest that participants spend on each activity?**

Close to 15 minutes. If I remember correctly from last year, all the groups I checked on had enough time to work on these problems.

**Comment by semaphoreP** [comment]
Thanks! I added an example using telescopes when I introduce classes. See PR #124.
