### ISSUE TITLE
Curriculum Review-- Day 3: Code Profiling 

### ISSUE THREAD

**Issue by vighnesh-nagpal** [semaphoreP/codeastro#123]
**How clear is the material? What’s confusing?**

The material is clearly presented, with great explanations of how to interpret the profiler output and how to then use that info to prioritise which parts of the code to improve. I also love the brief discussion on how to estimate scaling: very practically useful! The confusing parts are mostly due to the use of some undefined jargon (see below).

**Are we assuming any knowledge that we shouldn’t be? Where should we add background info?**

There was really one spot that stood out to me:

In the suggestions for how to speed up code: "If MKL/BLAS is being run inside of already-parallelized code, disable MKL/BLAS." It would be helpful to hyperlink explanations of what MKL/BLAS are and how to disable them

I also think it would be beneficial to include a sentence explaining what each element of the command "python -m cProfile -o profiler_output.txt profile_orbitize.py" does, for people not super familiar with it. 

**Is the structure of the lesson engaging? Are there any parts that are unnecessary/boring/too long?**

The structure is great, and the activities teach skills that are generalisable, which is awesome!

**How much time did it take you to complete the assignments? Keeping in mind that most participants will likely take more time than you, how much time should we suggest that participants spend on each activity?**

It took me around ~7-8 mins, so ~15 mins would be my suggestion for the participants.

**Comment by semaphoreP** [comment]
Thanks! I added a reference to the parallelism activity in Day4 for more info on MKL/BLAS, and expanded what the arguments mean in the profiler command.
