### ISSUE TITLE
Next year: ideas to help group formation

### ISSUE THREAD

**Issue by mwhosek** [semaphoreP/codeastro#129]
Some thoughts to make group formation easier next year:

- Ask participants ahead of time if they plan to participant synchronously or asynchronously (sorry if we have that info and I missed it). Group members should match in participation mode

- Have TA's make group text channels on discord ahead of time. Also include instructions for TAs on how to make private groups.

- For in-person groups, make room/location assignments for afternoon work ahead of time, if possible. 

Everyone: feel free to add onto this issue with more ideas on how to make group formation easier!

**Comment by sblunt** [comment]
This year we encouraged everyone to participate synchronously when they applied, so item 1 should not be a problem. We will implement items 2 and 3.
