### ISSUE TITLE
Gitflow demo was too fast to type along

### ISSUE THREAD

**Issue by sblunt** [semaphoreP/codeastro#130]
Noting feedback from participant this year that the gitflow demo was too fast to type along with.

**Comment by sblunt** [comment]
Matt, assigning you since you're doing gitflow this year. Up to you whether you want to encourage people to type along or not.

**Comment by mwhosek** [comment]
I believe we resolved this during our practice meeting today (Friday 7/7). I'll do a "type along" demo, but with instructions that folks should follow along if they get stuck (rather than try to debug)
