### ISSUE TITLE
Add github info earlier

### ISSUE THREAD

**Issue by Fasian1** [semaphoreP/codeastro#131]
Students sometimes have issues with pulling from main. To mitigate this, introduce git earlier or include something like this to install/prep steps. 

```
# this will stash your changes so you don't have conflicts. You can retrieve them again with git stash pop
git stash 

# pull latest from main
git pull origin main

# create a new branch called "day1"
git checkout -b day1
* do local stuff here* 

# this will switch your branch back to main from day1
git checkout main

# now you're updated with main again
git pull origin main 

# do day2 stuff now 
git checkout -b day2 
```

**Comment by sblunt** [comment]
Added git stash and git stash pop to intro slides. I'm not sure about having them create branches for each day-- I don't think they should need to actually change anything in the code/astro repo? We can encourage them to use/save the notebooks in colab.

**Comment by sblunt** [comment]
@Fasian1 let me know your thoughts!
