### ISSUE TITLE
Notes from Debrief Meeting

### ISSUE THREAD

**Issue by sblunt** [semaphoreP/codeastro#36]
General:
- Make sure we beta test everything (have at least one person do everything)
    - TAs & instructors should spend the month before code/astro starts testing all materials
- Cover the answers to the activities immediately after we all come together; post answer keys immediately afterward
    - in general we also need more time for activities
- Potentially 4 hours per day instead of 3 (one hour after lunch)?
- Make sure each day’s learning goals relate more explicitly to the overall workshop goals

Day 1:
- New structure for day 1:
    - Significant time spent on setup
        - include pip install -e .
        - Pip vs conda 
            - Where pip and conda should be installed
            - Make sure to conda install pip
        - Symlinks, paths
    - Development environments
    - Functional vs object oriented
        - Add discussion of inheritance
- Have backup virtual environment for those that don’t finish setup by end of day
    - Docker
    - VM
    - AWS 
- Remove mkl from reqs
- Remove astropy units from free-fall problem
- Move “ask a question on piazza” to day 1
- Potentially move package intros to day 2

Day 2:
- Incorporate actually interacting with git/github into activities
    - Fork Code/astro repo
    - Submit a pull request to main from your repo with small change (add your name)
- Want to improve the bug we fix in the debugging exercise
    - Potentially start with easier bug in smaller package; also have a larger orbitize bug as a challenge
    - Major issues:
        - Other bugs popped up (potentially solvable by using virtual environment)
        - Bug itself was confusing: issue with inputs, not code itself
        - Be ore clear about how to check out the broken_orbitize branch
- Future things to add to the debugging lesson:
    - Philosophy on how to fix bugs (not just find them)
    - Explicit instructions to configure python debug configuration (Especially CWD!!!)

Day 3:
- Docs:
    - Potentially have BJ demonstrate building docs from scratch
    - More TAs/instructors to go through/test sphinx instructions
    - Potentially include structured activities for a separate mini package
- Setup:
    - Need separate testpypi and pypi accounts
    - requirements.txt
    - Extra info on including auxiliary files
- Potentially remove profiling/keep as extra activity

Day 4:
- This day’s materials took more than expected (expected 2 hours, took 3)
- Testing:
    - Add more structured activities for a separate mini package

**Comment by sblunt** [comment]
More structure ideas: 
- recorded lectures & notebooks on "advanced topics." 
- move some lecture stuff into recorded lectures to watch beforehand (try to flip classroom) (TODO: identify stuff that can be recorded). (~10-15 mins of recorded material per day)

**Comment by semaphoreP** [comment]
Added more inheritance discussion and removed astropy units from free-fall problem in PR #42

**Comment by sblunt** [comment]
I'm going to close this, as I believe we've addressed most if not all of these.
