### ISSUE TITLE
Curriculum Review: Day 1 numpy & pandas

### ISSUE THREAD

**Issue by pranav-satheesh** [semaphoreP/codeastro#52]
- **Activity 1** assumes basic plotting using `matplotlib`, but I suppose this was already covered in the diagnostic assignment.
- **(Optional) Activity 3** requires knowledge of functions like `read_json`/` read_csv`. Maybe we can show one example of importing a CSV file in the Pandas section before the activities.

**Comment by bjfultn** [comment]
added an example of writing and reading to disk in Pandas demo section
