### ISSUE TITLE
Curriculum Review: Gitflow

### ISSUE THREAD

**Issue by mwhosek** [semaphoreP/codeastro#53]
I think the gitflow lesson is in great shape, and is really helpful. I only had a few comments, see "Content" section below. 

-------------------------------------
Prior Knowledge
Crucial things we assume you know?
---------------------------------------
Prior Lessons
-working knowledge of how git works
	-what code branches are in git
		-"main" branch contains primary code version
		-users can create additional branches off of "main", where they can make edits that don't impact "main". 
	-what it means to "git commit" and "git push"
	
Prior Experience
-Initial git experience from previous lesson will be important to keep folks from getting lost
	-how to make a git repository
	-how to run git commands from a terminal
	-familiarity with basic commands like commit and push
	-familiarity with GitHub online interface (for pull requests)

-------------------------------------
Content
Does everything work/make sense?
------------------------------------
Possible confusion "git merge" vs. pull requests: slides 7 - 11
	-Both involve merging code branches...in principle, these are interchangeable if one has the necessary permissions, right? But Pull Requests is preferred for git flow purposes? 

-I'm a bit confused by graphic on slide 7 for "git merge develop". I thought this command merges changes from development into the feature branch (e.g. text on slide: "grab any changes on develop"). But, I interpret the graphic as the feature is being merged into develop, which is what the Pull Request is supposed to do, right?

Potential useful thing to add: how to check which branch you are working on locally
	-while working between git branches, I find it useful to use "git status" command to confirm which branch I am currently working on. Otherwise, I find it is easy to forget which branch I'm actually on

-Didn't cover how to delete branch from command line (git branch -d feature). Is this important?

----------------------------------------------------------------------------------------
Learning Goals
Be able to use git and follow the git flow process to contribute to version-controlled code
-----------------------------------------------------------------------------------------

--> Yes, I think the slides do an excellent job of describing and visually showing the gitflow process. I was a little confused around the git-merging part (see comments), but otherwise I found the presentation to be clear.

**Comment by bjfultn** [comment]
- 6&7 reorganized slides to make the commands a little more clear
- noted 'git status' to check current branch
- I don't think I want to cover deleting branches via the command line because I never use it and can get you in a weird state with remote. Safer to do it on the web interface.
