### ISSUE TITLE
Curriculum Review: Software Testing

### ISSUE THREAD

**Issue by jeaadams** [semaphoreP/codeastro#55]
### Prior Knowledge: 

1.  Need to know how to write functions (Covered Day 1)
2. Examples require knowing numpy, astropy (Covered Day 1)

### Content:

I love these slides! The one thing I'll add here is that last year it was a little tricky for my group to complete the first exercise and get extensive help from the TA's during the class time  (the 1st Exercise asks participants to write three tests for their packages). I wonder if it could be at all helpful to have everyone write one simple test first to make sure they understand everything about testing conceptually. Random example: Maybe have them write a test to make sure ID numbers are less than 20 characters. Then they can try a few different random ID numbers to make sure it passes and fails accordingly. 

Edit: Rereading the slides, and I actually think it'll be fine, no need to add an extra example. I'll leave my thoughts above just in case though. 

### Learning Goals:

I think all the learning goals are achieved!

**Comment by bjfultn** [comment]
No changes needed
