### ISSUE TITLE
Curriculum Review: Discrimination in Software

### ISSUE THREAD

**Issue by jeaadams** [semaphoreP/codeastro#56]
### Prior Knowledge:

No prior knowledge needed.

### Content:

Awesome stuff! On slide 6, the last point is about using descriptive variable names. It might be helpful to give examples of what 'good' descriptive names are. This may already be covered in an earlier part of the workshop, so can maybe just be referenced. 

### Learning goals:
All achieved!

**Comment by semaphoreP** [comment]
Hi @jeaadams, good idea! I updated the slides for some examples. Let me know what you think!
