### ISSUE TITLE
Curriculum Review: Releasing Code

### ISSUE THREAD

**Issue by jeaadams** [semaphoreP/codeastro#57]
### Prior Knowledge:

I don't really think this assumes any prior knowledge. Maybe just important to make it clear _what_ a package even is relative to other things (like modules, for example). My first time creating and releasing a package was last year during this workshop and it took me a second to wrap my head around everything. 

### Content:

All awesome! These slides are really helpful

### Learning Goals:

All achieved!

**Comment by sblunt** [comment]
Excellent point, thanks @jeaadams! I updated the slides with a few extra about packages and modules. Let me know what you think. This suggestion also inspired me to come up with an idea for a new lesson on Python compilation and execution for next year, so thanks for that as well!
