### ISSUE TITLE
Curriculum Review: Day 1 astropy and matplotlib

### ISSUE THREAD

**Issue by vighnesh-nagpal** [semaphoreP/codeastro#58]
### Prior Knowledge

Matplotlib, astropy and numpy need to be installed, as well as orbitize. 

The tutorial also assumes working knowledge of numpy, which builds on the previous part of Day 1. 

The part of the tutorial in which we run an orbit fit and create an orbit plot using orbitize also assumes that participants are familiar with the concept of random sampling.

### Content

Matplotlib: 

- The link to the page describing the Figure object (below cell 3) is broken. Here's the correct link: [Figure](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.figure.html)

- I think it would be good to have a demonstration of matplotlib's notebook mode (just a single cell) and how we can use that to interact with plots in a jupyter notebook -- its a really nifty feature!

- Activities look great!

Astropy:

Everything looks great, and the activities look fun!

### Learning Goals

Overall, this session looks awesome and gives a great primer for matplotlib and astropy!

**Comment by sblunt** [comment]
Great point about assuming knowledge of random sampling, @vighnesh-nagpal. I'll definitely keep that in mind when going over the activities. I also fixed the Figure link.

Thanks for the point about matplotlib notebook. Unfortunately I don't think that feature works in VSCode-- perhaps we could just mention it in text in the tutorial?

**Comment by sblunt** [comment]
Addressed in PR #75 -- feel free to reopen if anything wasn't satisfactorily addressed.
