### ISSUE TITLE
Curriculum Review: Day 2 Git Introduction

### ISSUE THREAD

**Issue by vighnesh-nagpal** [semaphoreP/codeastro#59]
### Prior Knowledge

Assumes familiarity with the existence of Git/Github. 

### Content

Overall, things look really good! The commit tree diagrams are effective and clear to understand, while the explanations behind how commits build on each other and how that relates to branches also make sense. 

However, I think that the section about merge conflicts could be expanded on a little bit: It's not clear what exactly constitutes a conflict and how partially overlapping codes are handled during the merge process. A bit more explanation of how this works would be really beneficial imo. 

The conceptual activities are great too!

### Learning Goals

I think this session does a great job of explaining the fundamentals of how git works!

**Comment by semaphoreP** [comment]
Thanks! I added a couple of slides showing the merging process. Let me know what you think!

https://drive.google.com/file/d/1ybHcKcaaamoUJ2DspuG-bpVbvsk5_CkV/view?usp=sharing

**Comment by vighnesh-nagpal** [comment]
Thanks for adding them in, and I like the slides!
