### ISSUE TITLE
Curriculum Review: Day 1 Numpy and Pandas

### ISSUE THREAD

**Issue by Devagio** [semaphoreP/codeastro#62]
### Prior Knowledge
Assumes absolutely nothing beyond the contents of the diagnostic.

### Content
All okay. Everything seems to work fine.

### Learning Goals
1. Pandas section completely fulfills all the basic learning goals.
2. Numpy fulfills most of the basic learning goals, addition of copy methods is probably a good idea, and some other optional topics are stacking and other interactions between two arrays.

**Comment by bjfultn** [comment]
added examples of stacking and copying
