### ISSUE TITLE
Curriculum Review: Day 2 Git Introduction

### ISSUE THREAD

**Issue by pranav-satheesh** [semaphoreP/codeastro#63]
## Prior Knowledge
Some basics of Git and some terminal commands

## Content

- The content looks really good. The gitflow diagrams are perfect and it really helps folks understand the concept of gitflow well. Also, the exercises are also perfect.

- I have one small comment regarding merging the new branch and merge conflicts. Maybe you can also show how merging and pull requests work on the GitHub website. This will also make the comparison of the two branches and help resolve any merge conflicts.

## Learning Goals

Overall, I think the slides + activities does a great job explaining the git fundamentals.

**Comment by semaphoreP** [comment]
Thanks! I added a couple of slides showing manual merges here: https://drive.google.com/file/d/1ybHcKcaaamoUJ2DspuG-bpVbvsk5_CkV/view?usp=sharing

I think Github stuff is discussed more in BJ's Gitflow lesson plan so I'm not going to include it here.
