### ISSUE TITLE
Curriculum Review: Day 3 Code Profiling

### ISSUE THREAD

**Issue by PauliPalbi** [semaphoreP/codeastro#67]
### Prior knowledge:
On the first line of the .ipynb I would specify that the output of the profiler is the output of running the code profile_orbitize.py in case someone is not in the class. 

### Content:
Regarding the content, first, I was not able to run profile_orbitize. This due to 2 reasons:
1. I think the command line should specify that it runs on python3 
 `python3 -m cProfile -o profiler_output.txt profile_orbitize.py`
2. I cloned orbitize as specified on the instructions and it did not import it. It import it as orbitize.orbitize if I move it to Day3. Maybe this is easy to solve, but it didn't runned for me on the first try.

Apart, I would add the link to the documentation of pstats in case someone is interested.

I like the activities. I remember I had a good time las year doing them. :D

In general everything is nice, maybe too much text on the notebook, but is okey, everything well explained.

### Learning goals:
Good learning goals :D. I would specify it on the .ipynb first paragraph just for it to be clear. I mean, "Profile the run time of your code and identify the computational bottlenecks".
I think the objective is fulfilled with the lesson. Maybe even more than that, I mean, the activities give a better understanding on how the code works, not just on run time and bottlenecks, so that is very nice!

**Comment by semaphoreP** [comment]
Ok I added these changes in PR #73. I think the current python configuration we have students use should work with python and not python3, and the orbitize import _should_ work. I added a sentence to caution that their setup could be different and to ask a TA for help if needed.
