### ISSUE TITLE
how does a person know if something is already installed

### ISSUE THREAD

**Issue by sndik16** [semaphoreP/codeastro#70]
I suggest to add after this sentence
"We'll also install cython and jupyter notebooks this way if they are not already installed. "

an explanation how to check if it is installed or not, e.g. 
"You can run **conda list** command in codeastro base to check if you already have jupyter or cython."

References: https://docs.anaconda.com/anaconda/install/verify-install/

**Comment by semaphoreP** [comment]
Thanks for the suggestion. Added!
