### ISSUE TITLE
Curriculum Review: Day 2 Debugging

### ISSUE THREAD

**Issue by mwhosek** [semaphoreP/codeastro#72]
Overall I think this lesson is in good shape and addresses the learning goal, which is for folks to learn how to interactively debug code using breakpoints, and not rely on print statements. One possible hiccup I see is that the lesson may be difficult if participants are not comfortable working in VSCode, which could slow down their progress in the debugging activity. However, I think this can be addressed by individual TA help in the breakout rooms as it comes up. 

Prior Knowledge
Crucial things we assume you know?
==================

Prior Lessons
--------------
-python variable data types
-array indexing

Prior Experience
----------------
-Ability to setup and run code in VSCode
	-how to load a python file in the editor
	-running code in debug mode
	-setting breakpoints and navigating debugger

-installing broken orbitize and running it

-Following multiple levels of sub-function calls within a given function

Content
Does everything work/make sense?
==============
This lesson relies on Jason's debugging demonstration to teach folks how to use VSCode and debug their code. The demonstration notes appear to cover everything the participants will need to do complete the activity.

**Comment by semaphoreP** [comment]
Thanks for the review! Yeah, maybe in future years we could make some tutorial videos to help with the setup. I do want people to spend some time to learn how to use a debugger, but I agree that it's a bit finicky. Hopefully we can address any issues that arise!
