### ISSUE TITLE
Curriculum Review: Day 3- Docs

### ISSUE THREAD

**Issue by vighnesh-nagpal** [semaphoreP/codeastro#76]
### Prior Knowledge 

This tutorial doesn't seem to assume much prior knowledge, other than familiarity with docstrings. 

### Content

Things look good overall! However there is one typo in the README that causes import errors:

In _step 7_ , we should add "sphinx.ext.napole**o**n" instead of "sphinx.ext.napole**a**n" to extensions in conf.py. The file in sphinx.ext is called napoleon, so the current instructions lead to import errors. Changing the spelling fixed the issue. 

Other than that, the tutorial is informative and easy to follow!

### Learning Goals 

All met!

**Comment by bjfultn** [comment]
good catch, fixed!
