### ISSUE TITLE
Mac install: specifying python number for codeastro conda

### ISSUE THREAD

**Issue by mwhosek** [semaphoreP/codeastro#86]
Hello,

When I was installing the codeastro conda environment, I found that I needed to specify that I wanted to install python version 3.7:

`conda create -n codeastro python=3.7`

rather than the current:

`conda create -n codeastro python=3`

Otherwise, the conda install of numpy, cython, and jupyter crashes because it is looking for a conda directory named `'/Users/mwhosek/.conda/envs/codeastro/bin/python3.7'`, but the conda create command calls the directory `'/Users/mwhosek/.conda/envs/codeastro/bin/python'` instead (with python 3.6.9 installed). 

This problem is resolved when I specified that I wanted to make the environment python=3.7. My directory is still named `'/Users/mwhosek/.conda/envs/codeastro/bin/python'` but the `conda install numpy cython jupyter` works.

This issue could be because my version of conda is quite old (4.5.4). In any case, I think specifying python=3.7 in the conda create step doesn't hurt?

Thanks!
Matt

**Comment by mwhosek** [comment]
Ah, good point. Yes, my install works if I specify python=3.9 when creating the conda environment. But, it wouldn't have used that version of python unless it was specified.

**Comment by semaphoreP** [comment]
Ok thanks for checking! Would you mind editing the text to reflect that (with maybe a note to use whatever is the most recent version of python 3?).

**Comment by mwhosek** [comment]
Sure, I will do that. It looks like the most recent version of python 3 is 3.10...I will try running the installation instructions with 3.10, and if it works, I'll update the command to `conda create -n codeastro python=3.10.` Otherwise, I'll have it specify python 3.9

**Comment by mwhosek** [comment]
Pull request submitted! Since I'm only familiar with mac, I wasn't able to check if the windows installation needs a similar update. I defer that to the windows folks.

**Comment by sblunt** [comment]
Merged in PR #87
