### ISSUE TITLE
Discrimination in Software TA Review

### ISSUE THREAD

**Issue by briley-lewis** [semaphoreP/codeastro#90]
Material is clear, but doesn't seem very interactive -- consider adding in places to ask participants to share things they've noticed/experienced and to think about big questions to facilitate more in depth and meaningful discussion/thought on these issues. I think the only knowledge assumed is stuff that people are likely to have encountered in everyday life, so it's ok. Suggestions for further reading would be welcome too, for people who are interested in this and want to learn more (e.g. Algorithms of Oppression by Safiya Noble).

**Comment by Palma-Bifani** [comment]
Hi, I have similar comments :) I once made a similar presentation and I will attach some interesting slides. 
[https://drive.google.com/drive/folders/1tGqF4w9DsMjWWchiyVhVLr1iATKGHjds?usp=sharing](https://drive.google.com/drive/folders/1tGqF4w9DsMjWWchiyVhVLr1iATKGHjds?usp=sharing)

- I think that adding some slides related to gender discrimination could be very nice. First slide attached is about binarity in face recognition softwares. 
- Second and third are about general inequality related to science productivity. 
- The forth slide isa out LGBBTQ+ and quitting science. 
- I think it could be very nice to add something like on slide five, where we show where they can take tests and check their intrinsic biases. 
- Final slide is important too, usually universities have protocols and I think this could e a good instance to mention that. Everybody should be aware that they are official ways to deal with uncomfortable/vulnerability situations. 

If you want to include some parts of what I mentioned, I'm happy to help further.

**Comment by Palma-Bifani** [comment]
(I will post my new-review under this other one, to avoid opening too many issues)

- How clear is the material? What’s confusing?

The material is very clear :) About slide 15, I'm not sure what is the goal of those pictures: "Not all astronomers are telescopes"

- Are we assuming any knowledge that we shouldn’t be? Where should we add background info?

I think this is a very general overview of the topic, which is okay for this purpose. Talking about existing protocols in educational institutes could be very nice. Not in detail, but mentioning it.


- Is the structure of the lesson engaging? Are there any parts that are unnecessary/boring/too long?

I like the lesson a lot. Maybe I would add small things, as I said in my comment above...


- How much time did it take you to complete the assignments?

The implicit bias test is a very nice addition but it is too long as an assignment during the lesson. It took me around 15 min probably.

**Comment by semaphoreP** [comment]
Thanks both! I changed up the activity to be something shorter to think about what biases exist in machine learning. I also added a slide on addressing discriminatory behavior including institutional resources.
