### ISSUE TITLE
Curriculum Review: Day 1 - Numpy & Pandas

### ISSUE THREAD

**Issue by chetanchawla** [semaphoreP/codeastro#92]
### **How clear is the material? What’s confusing?**
- The material is pretty clear and straightforward. It is well structured and I found it highly readable and comprehensible.

### **Are we assuming any knowledge that we shouldn’t be? Where should we add background info?**
- No, the tutorial starts from the basics and builds its way up to help us with the included activities. The provided background information through the supporting text cells was enough to understand the context and functionalities well.

### **Is the structure of the lesson engaging? Are there any parts that are unnecessary/boring/too long?**
- The to-do parts are pretty engaging, and the tutorial length is perfect. 

### **How much time did it take you to complete the assignments? Keeping in mind that most participants will likely take more time than you, how much time should we suggest that participants spend on each activity?**
- The first activity took me ~6 minutes. So, 6-8 minutes should be good (also considering that they are working in groups). The second activity is pretty small and mainly prompts for a small discussion between the group members. So, they are likely to finish it in ~2 minutes. Overall, I think 10 minutes should be good. (Not including optional activities)

### **Additional Comments**
- We are asking the question ```if arrays have fixed size, how do you think numpy.append works?``` from the participants in the first text cell. I think we should also include its answer explicitly in the Key.
- I couldn't find the files for the Optional Activity 3 in the Google colab folder (both in the tutorial and the key). We need to include the star_names.json file at the path - ```../example_data/star_names.json ```

**Comment by sblunt** [comment]
Thanks Chetan! Excellent comments. I'll change the answer key to address this, and I'll make sure the paths in the colab are correct (good catch).

**Comment by sblunt** [comment]
Just updated the solution in the drive @chetanchawla; let me know what you think.

**Comment by sblunt** [comment]
PR to address path issue: #94

**Comment by chetanchawla** [comment]
Thanks Sarah, everything looks good now!
