### ISSUE TITLE
Curriculum Review: Day 1 - Matplotlib & Astropy

### ISSUE THREAD

**Issue by chetanchawla** [semaphoreP/codeastro#93]
### **How clear is the material? What’s confusing?**
- The material got a bit confusing at one point for the Matplotlib tutorial. I think we can write the following in more layman's terms, as it goes into very deep intricacies of how matplotlib really works, which are often not very useful while using the library, and got me a bit confused.
- ```matplotlib.pyplot relies on the concept of changing state. You can think of the state of any environment (your bash shell, for example, or the iPython prompt) as a list of pre-loaded variables and commands that control default behaviors. Some of these variables are mutable, meaning that you can change them with your programming needs. Changing mutable state variables just means updating the default behavior of your environment.```
- Other than this, the material was very readable and easily understandable!

### **Are we assuming any knowledge that we shouldn’t be? Where should we add background info?**
- No. Though, as a suggestion (not really sure if it should be implemented), we can probably place the general tips right before the Activities section in the matplotlib tutorial. Having those tips in the very beginning might not be very useful as I needed to scroll back up anyway to look at them again.

### **Is the structure of the lesson engaging? Are there any parts that are unnecessary/boring/too long?**
- Yes! The lesson is very engaging (Especially due to orbitize!) 😄

### **How much time did it take you to complete the assignments? Keeping in mind that most participants will likely take more time than you, how much time should we suggest that participants spend on each activity?**
- It took me ~5-6 minutes for matplotlib activities and ~3-4 minutes for astropy assignment. I think overall ~12-15 minutes should be good for participants (excluding the optional activities).

**Additional Comments**
- **Installing orbitize**: We need to add a cell for installing orbitize, as it is not there by default ```!pip install orbitize```
- **Matplotlib Activity 1, pt.1**: It asks us to change xlim in top-right plot, but changes it in bottom-right plot in the Key
- **Matplotlib Activity 1** - has an extra orange star in the pre-rendered image
- **Matplotlib Activity 1** - The code line ```plt.savefig('{}/Desktop/fig.png'.format(os.path.expanduser('~')))``` in the Key gives an error: ```[Errno 2] No such file or directory: '/root/Desktop/fig.png'```. I think we can replace it with ```plt.savefig('./fig.png')``` to simplify things and save it in the ```content``` folder itself(the current working directory for everyone on Colab)

**Comment by sblunt** [comment]
Addressed in PR #96

**Comment by chetanchawla** [comment]
Everything looks great now, Sarah! I feel that the state explanation is a lot easier to understand now! Thanks!
