### ISSUE TITLE
Curriculum Review: Day 3 Code Documentation

### ISSUE THREAD

**Issue by briley-lewis** [semaphoreP/codeastro#97]
First off, A+ memes.

I am curious what all the files sphinx-quickstart makes are. I remember having trouble with Sphinx last year, and I wonder if more knowledge of how it's doing things (so it's less of a black box) could help with that. I could be totally wrong, maybe it's a Pandora's box situation. Also, step 10 doesn't feel abundantly clear to me now, and that is also where I remember getting lost as a participant.

**Comment by briley-lewis** [comment]
Yes, very helpful! This looks awesome and answers many questions I had. Also, now I see the screenshots -- sorry, they weren't loading when I was on the very very bad AAS conference wifi :) 

I do still have one question about `toctree` though. It would be helpful, at least for me to understand how things are working, exactly what maxdepth & caption mean in that command. 

Also, I feel like I am still a bit confused exactly on the formatting of the index.rst file — e.g. the ..(command):: structure, what marking words with `` does. I'm not super familiar with rst files, and I think it may be worth mentioning that this is essentially a sort of text file, and maybe linking to something with more info for those who want to learn more.

**Comment by mwhosek** [comment]
Sounds good! I've added more information in the "Tips and Tricks" section with details regarding the different sphinx commands used in the example, which hopefully addresses your questions (merged into main 6/20). This section also includes a link to a cheatsheet on how to format rst files (I'll say what rst files are verbally during the lesson). I don't think I'll walk through this "Tips and Tricks" section during the lesson for the sake of time, but I'll point it out to participants so they can reference it as they wish. 

Let me know if this falls in-line with what you were thinking. Thanks again!

**Comment by briley-lewis** [comment]
Fantastic! Thanks so much
